"""Builds the portable install.sh from the user's selections."""
import base64
import datetime
import os

from . import mapping
from .distro import pm_for_family

INSTALL_SNIPPETS = {
    "apt": (
        "install_pkg() {\n"
        '  DEBIAN_FRONTEND=noninteractive apt-get install -y "$1"\n'
        "}\n"
        "apt-get update -y || true\n"
    ),
    "dnf": (
        "install_pkg() {\n"
        '  dnf install -y "$1"\n'
        "}\n"
    ),
    "pacman": (
        "install_pkg() {\n"
        '  pacman -S --noconfirm --needed "$1"\n'
        "}\n"
        "pacman -Sy || true\n"
    ),
    "zypper": (
        "install_pkg() {\n"
        '  zypper --non-interactive install "$1"\n'
        "}\n"
    ),
    "apk": (
        "install_pkg() {\n"
        '  apk add "$1"\n'
        "}\n"
        "apk update || true\n"
    ),
}


def _embed_script_block(path):
    with open(path, "rb") as f:
        data = base64.b64encode(f.read()).decode("ascii")
    dest = path  # reinstall at the same absolute path
    return (
        f"echo 'Restoring custom script: {dest}'\n"
        f"mkdir -p \"$(dirname '{dest}')\"\n"
        f"base64 -d > '{dest}' <<'MOVOUT_EOF'\n{data}\nMOVOUT_EOF\n"
        f"chmod +x '{dest}'\n"
    )


def build_script(source_info, target_family, packages, services, custom_scripts):
    """packages/services: list of selected canonical names.
    custom_scripts: list of absolute paths to embed.
    Returns the full shell script content as a string.
    """
    pm = pm_for_family(target_family)
    lines = []
    lines.append("#!/usr/bin/env bash")
    lines.append("# Generated by MovingOut (movout)")
    lines.append(f"# Source: {source_info.get('name')} ({source_info.get('package_manager')})")
    lines.append(f"# Target: '{target_family}' family ({pm})")
    lines.append(f"# Created on: {datetime.datetime.now().isoformat(timespec='seconds')}")
    lines.append("set -uo pipefail")
    lines.append('FAILED_LOG="./movingout-failed.log"')
    lines.append(': > "$FAILED_LOG"')
    lines.append("")
    lines.append(INSTALL_SNIPPETS.get(pm, INSTALL_SNIPPETS["apt"]))
    lines.append("")

    lines.append('echo "== MovingOut: installing packages =="')
    for pkg in packages:
        target_name = mapping.translate(pkg, target_family)
        lines.append(
            f'install_pkg "{target_name}" || echo "{pkg} -> {target_name}" >> "$FAILED_LOG"'
        )
    lines.append("")

    if services:
        lines.append('echo "== MovingOut: enabling services =="')
        for svc in services:
            lines.append(
                f'systemctl enable --now "{svc}" 2>>"$FAILED_LOG" '
                f'|| echo "service {svc} not enabled" >> "$FAILED_LOG"'
            )
        lines.append("")

    if custom_scripts:
        lines.append('echo "== MovingOut: restoring custom scripts =="')
        for path in custom_scripts:
            lines.append(_embed_script_block(path))
        lines.append("")

    lines.append('echo "== MovingOut: done =="')
    lines.append('if [ -s "$FAILED_LOG" ]; then')
    lines.append('  echo "Some items failed, see $FAILED_LOG"')
    lines.append("fi")
    lines.append("")
    return "\n".join(lines)


def write_script(content, out_path):
    with open(out_path, "w") as f:
        f.write(content)
    os.chmod(out_path, 0o755)
    return out_path
