"""Detects MovingOut-generated porting scripts already sitting on this machine,
so the TUI can offer an "install mode" (run an existing script) alongside the
normal "create a new script" flow.
"""
import os
import re

MARKER = "# Generated by MovingOut (movout)"
TARGET_RE = re.compile(r"#\s*Target:\s*'([^']+)'\s*family")

# Shallow, non-recursive scan of the places a porting script is realistically
# copied to before running it. A full recursive filesystem walk would be slow
# and noisy (permission errors everywhere), so we keep this list intentionally
# small and easy to extend.
BASE_DIRS = [
    ".",
    os.path.expanduser("~"),
    os.path.expanduser("~/Downloads"),
    os.path.expanduser("~/Desktop"),
    "/tmp",
]

# Users tend to keep porting scripts in a dedicated folder named after the
# tool itself -- check those too, inside every base dir above.
NAMED_SUBDIRS = ["movingout", "movout"]


def _candidate_dirs():
    dirs = list(BASE_DIRS)
    for base in BASE_DIRS:
        for sub in NAMED_SUBDIRS:
            dirs.append(os.path.join(base, sub))
    return dirs


def _looks_like_movout_name(name):
    """Fast filename-level signature check: every file movout generates is
    named 'movingout-install-<family>.sh' (or a user-chosen name that still
    typically mentions the tool), so require that hint before bothering to
    open and parse the file."""
    lowered = name.lower()
    return "movout" in lowered or "movingout" in lowered


def _read_head(path, max_lines=15):
    lines = []
    try:
        with open(path, "r", errors="ignore") as f:
            for _ in range(max_lines):
                line = f.readline()
                if not line:
                    break
                lines.append(line)
    except OSError:
        pass
    return lines


def _extract_target_family(head_lines):
    for line in head_lines:
        m = TARGET_RE.search(line)
        if m:
            return m.group(1)
    return None


def find_generated_scripts(current_family=None):
    """Scan common locations (plus any 'movingout'/'movout' subfolder inside
    them) for .sh files generated by a previous `movout` run.

    When current_family is given, only scripts built for that same target
    family are returned: a porting script generated for Arch has no business
    being offered for install on a Debian box, so the auto-scan only ever
    surfaces scripts that match the system it is running on.

    Returns a sorted, de-duplicated list of absolute paths.
    """
    found = set()
    for d in _candidate_dirs():
        try:
            entries = os.listdir(d)
        except OSError:
            continue
        for name in entries:
            if not name.endswith(".sh") or not _looks_like_movout_name(name):
                continue
            full = os.path.join(d, name)
            if not os.path.isfile(full):
                continue
            head = _read_head(full)
            if not any(MARKER in line for line in head):
                continue
            if current_family is not None:
                family = _extract_target_family(head)
                if family != current_family:
                    continue
            found.add(os.path.abspath(full))
    return sorted(found)
