"""Detects MovingOut-generated porting scripts already sitting on this machine,
so the TUI can offer an "install mode" (run an existing script) alongside the
normal "create a new script" flow.
"""
import os

MARKER = "# Generated by MovingOut (movout)"

# Shallow, non-recursive scan of the places a porting script is realistically
# copied to before running it. A full recursive filesystem walk would be slow
# and noisy (permission errors everywhere), so we keep this list intentionally
# small and easy to extend.
SEARCH_DIRS = [
    ".",
    os.path.expanduser("~"),
    os.path.expanduser("~/Downloads"),
    os.path.expanduser("~/Desktop"),
    "/tmp",
]


def _looks_generated(path):
    try:
        if os.path.getsize(path) > 20 * 1024 * 1024:
            return False
        with open(path, "r", errors="ignore") as f:
            for _ in range(10):
                line = f.readline()
                if not line:
                    break
                if MARKER in line:
                    return True
    except OSError:
        pass
    return False


def find_generated_scripts():
    """Scan common locations for .sh files generated by a previous `movout` run.
    Returns a sorted, de-duplicated list of absolute paths.
    """
    found = set()
    for d in SEARCH_DIRS:
        try:
            entries = os.listdir(d)
        except OSError:
            continue
        for name in entries:
            if not name.endswith(".sh"):
                continue
            full = os.path.join(d, name)
            if not os.path.isfile(full):
                continue
            if _looks_generated(full):
                found.add(os.path.abspath(full))
    return sorted(found)
